CREATE TABLE IF NOT EXISTS dtp_entidades (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  excluidos jsonb NOT NULL DEFAULT '[]'::jsonb,
  extra jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS dtp_entidades_nome_unico ON dtp_entidades (lower(trim(nome)));

ALTER TABLE cursos_gold ADD COLUMN IF NOT EXISTS entidade_responsavel_id integer REFERENCES dtp_entidades(id) ON DELETE SET NULL;

ALTER TABLE curso_dtp_modelos ADD COLUMN IF NOT EXISTS incluidos jsonb NOT NULL DEFAULT '[]'::jsonb;
