/** Os 14 tópicos do dossiê da financiada, com a pasta de cada um na Drive. */
export const TOPICOS_FIN = [
  { n: 1, pasta: "1. Enquadramento da ação", label: "Enquadramento da ação", hint: "Aprovação, arranque, cronograma, programa e regulamentos." },
  { n: 2, pasta: "2. Recursos pedagógicos e materiais didáticos", label: "Recursos pedagógicos e materiais", hint: "Manuais, textos de apoio e protocolo de cedência de espaços." },
  { n: 3, pasta: "3. Formadores", label: "Formadores", hint: "Seleção, identificação, habilitações, CV, CCP, contrato e honorários." },
  { n: 4, pasta: "4. Equipa Técnica", label: "Equipa técnica", hint: "Listagem da equipa pedagógica." },
  { n: 5, pasta: "5. Formandos", label: "Formandos", hint: "Seleção, fichas, RGPD, contratos e a documentação de cada formando." },
  { n: 6, pasta: "6. Registos de assiduidade e de desenvolvimento das sessões", label: "Assiduidade e sessões", hint: "Presenças, planos, justificação de faltas, ocorrências e reclamações." },
  { n: 7, pasta: "7. Ferramentas e critérios de avaliação da aprendizagem", label: "Avaliação da aprendizagem", hint: "Diagnóstico, teste final, corrigenda, grelha e pauta assinadas." },
  { n: 8, pasta: "8. Mecanismos de avaliação à ação formativa", label: "Avaliação da ação", hint: "Inquéritos, diagnóstico de necessidades e o relatório final gerado pelo GesForma." },
  { n: 9, pasta: "9. Processos e ferramentas de supervisão e apoio pedagógico", label: "Supervisão pedagógica", hint: "Relatório inicial, intermédio e final." },
  { n: 10, pasta: "10. Plano de informação e divulgação da oferta formativa", label: "Divulgação", hint: "Folheto de divulgação da ação." },
  { n: 11, pasta: "11. Certificados", label: "Certificados", hint: "Cópia dos certificados emitidos e comprovativo de entrega." },
  { n: 12, pasta: "12. Princípios de equidade e inclusão", label: "Equidade e inclusão", hint: "Checklist de igualdade de oportunidades." },
  { n: 13, pasta: "13. Articulação com Academia Digital", label: "Academia Digital", hint: "Reporte do Portal Academia Portugal Digital." },
  { n: 14, pasta: "14. Avaliação de impacto pós-formação - 3 meses", label: "Impacto pós-formação", hint: "Inquéritos e relatório três meses depois. Só as respostas desta turma." },
] as const;

const POR_ID: Record<string, number> = {
  notificacao: 1,
  "comunicacao-arranque": 1,
  cronograma: 1,
  programa: 1,
  regulamento: 1,
  "regulamento-formando": 1,
  "id-turma": 1,
  ufcd: 1,
  enquadramento: 1,
  materiais: 2,
  "protocolo-espacos": 2,
  instalacoes: 2,
  "selecao-formadores": 3,
  "id-formador": 3,
  "habil-formador": 3,
  "cv-formador": 3,
  "ccp-formador": 3,
  "ficha-dgert": 3,
  "formacao-complementar": 3,
  "contrato-formador": 3,
  honorarios: 3,
  equipa: 4,
  "selecao-formandos": 5,
  "listagem-formandos": 5,
  fichas: 5,
  "rgpd-contratos": 5,
  cc: 5,
  ch: 5,
  "entidade-patronal": 5,
  morada: 5,
  iban: 5,
  "seguro-formandos": 5,
  "mapa-pagamento": 5,
  "cv-formando": 5,
  emprego: 5,
  "contratos-f": 5,
  rgpd: 5,
  presencas: 6,
  planos: 6,
  "justificacao-faltas": 6,
  ocorrencias: 6,
  reclamacao: 6,
  sumarios: 6,
  horas: 6,
  "teste-diagnostico": 7,
  "teste-final": 7,
  corrigenda: 7,
  "grelha-correcao": 7,
  pauta: 7,
  instrumentos: 7,
  "inquerito-formador": 8,
  "inquerito-formandos": 8,
  "diagnostico-necessidades": 8,
  "relatorios-estatisticos": 8,
  relatorio: 8,
  satisfacao: 8,
  execucao: 8,
  "relatorio-inicial": 9,
  "relatorio-intermedio": 9,
  "relatorio-supervisao": 9,
  supervisao: 9,
  folheto: 10,
  divulgacao: 10,
  certificados: 11,
  "entrega-certificados": 11,
  equidade: 12,
  academia: 13,
  "inqueritos-pos": 14,
  "relatorio-pos": 14,
  "inqueritos-turma": 14,
};

export function topicoFinDe(id: string) {
  return POR_ID[id.replace(/^extra:/, "")] ?? 1;
}

export function pastaTopicoFin(n: number) {
  return TOPICOS_FIN.find(t => t.n === n)?.pasta ?? TOPICOS_FIN[0].pasta;
}

export function pastaFinDoItem(id: string) {
  return pastaTopicoFin(topicoFinDe(id));
}
