export const TOPICOS_FIN = [
  { n: 1, label: "Enquadramento da ação", hint: "Aprovação, arranque, cronograma, programa e regulamentos." },
  { n: 2, label: "Recursos pedagógicos e materiais", hint: "Manuais, textos de apoio e protocolo de cedência de espaços." },
  { n: 3, label: "Formadores", hint: "Seleção, identificação, habilitações, CV, CCP, contrato e honorários." },
  { n: 4, label: "Equipa técnica", hint: "Listagem da equipa pedagógica." },
  { n: 5, label: "Formandos", hint: "Seleção, fichas, RGPD, contratos e a documentação de cada formando." },
  { n: 6, label: "Assiduidade e sessões", hint: "Presenças, planos, justificação de faltas, ocorrências e reclamações." },
  { n: 7, label: "Avaliação da aprendizagem", hint: "Diagnóstico, teste final, corrigenda e grelha assinada entram por upload. A pauta sai da grelha. A nota do Moodle lança-se à mão." },
  { n: 8, label: "Avaliação da ação", hint: "Inquéritos, diagnóstico de necessidades e o relatório final gerado pelo GesForma." },
  { n: 9, label: "Supervisão pedagógica", hint: "Relatório inicial, intermédio e final." },
  { n: 10, label: "Divulgação", hint: "Folheto de divulgação da ação." },
  { n: 11, label: "Certificados", hint: "Cópia do certificado obtido fora do GesForma e comprovativo de entrega gerado a partir desses PDFs." },
  { n: 12, label: "Equidade e inclusão", hint: "Checklist de igualdade de oportunidades." },
  { n: 13, label: "Academia Digital", hint: "Reporte do Portal Academia Portugal Digital." },
  { n: 14, label: "Impacto pós-formação", hint: "Inquéritos e relatório três meses depois. Só as respostas desta turma." },
] as const;
